<?php
/**
 * @file
 * Code for the Kendra API Services feature.
 */

include_once('kendra_api_services.features.inc');
include_once('kendra_api_services.resources.inc');


/**
 * Provide a default callback for a resource which doesn't define one
 *
 * @return string
 */
function _kapi_default_callback($funcname = 'undefined') {
	return sprintf(t("No callback has been defined for this controller. [%s]"),$funcname);
}

/**
 * Implementation of hook_services_resources().
 */
function kendra_api_services_services_resources() {
	$resources = kendra_api_services_services_get_mappings();
	return $resources;
}
